import { directionPalette } from '../services/palette.js'

function arr(v) {
  return Array.isArray(v) ? v : v ? [v] : []
}

const DNA_LABELS = {
  color: 'Color', typography: 'Typography', composition: 'Composition',
  lighting: 'Lighting', photography: 'Photography', people: 'People',
  material: 'Material', graphicLanguage: 'Graphic Language',
}

function dimText(dna) {
  return Object.entries(DNA_LABELS)
    .map(([k, label]) => {
      const dim = dna[k]
      if (!dim) return ''
      return `### ${label} — Visual DNA

**Principle:** ${dim.principle || '—'}

**DO:**
${arr(dim.do).map((x) => `- ${x}`).join('\n') || '- _none_'}

**DON'T:**
${arr(dim.dont).map((x) => `- ${x}`).join('\n') || '- _none_'}
`
    })
    .join('\n')
}

export function exportMarkdown(p) {
  const b = p.brandCore || {}
  const brief = p.visualBrief || {}
  const dir = p.selectedDirection || {}
  const logo = p.selectedLogo || {}
  const rules = p.visualRules || {}
  const pal = directionPalette(dir)
  const dna = rules.visualDNA || {}

  const lines = []
  lines.push(`# ${b.brandName || 'Brand'} — Visual Rules`, '')
  lines.push(`> Generated by Brand Visual Workflow. _Image links below are temporary (≈24h)_ — for a self-contained guide use Export HTML.`, '')

  lines.push('## Brand Core', '')
  if (b.brandName) lines.push(`**Brand Name:** ${b.brandName}`)
  if (b.purpose) lines.push(`**Purpose:** ${b.purpose}`)
  if (b.promise) lines.push(`**Promise:** ${b.promise}`)
  if (b.positioning) lines.push(`**Positioning:** ${b.positioning}`)
  if (b.personality) lines.push(`**Personality:** ${b.personality}`)
  if (b.tagline) lines.push(`**Tagline:** ${b.tagline}`)
  lines.push('')

  lines.push('## Visual Brief', '')
  if (brief.brandEssence) lines.push(`**Brand Essence:** ${brief.brandEssence}`)
  if (brief.desiredPerception) lines.push(`**Desired Perception:** ${brief.desiredPerception}`)
  if (brief.visualPersonality) lines.push(`**Visual Personality:** ${brief.visualPersonality}`)
  for (const [k, label] of [['visualKeywords', 'Visual Keywords'], ['emotionalKeywords', 'Emotional Keywords']]) {
    if (arr(brief[k]).length) lines.push(`**${label}:** ${arr(brief[k]).join(', ')}`)
  }
  lines.push('')

  if (dir.name) {
    lines.push('## Selected Visual Direction', '', `### ${dir.name}`, '', dir.coreIdea || '', '')
    if (pal.length) lines.push(`**Palette:** ${pal.map((h, i) => `${['Primary', 'Secondary', 'Aux 1', 'Aux 2'][i] || ''} ${h}`).join(' · ')}`, '')
    if (dir.heroImage) lines.push(`![Hero](${dir.heroImage})`, '')
    for (const [k, label] of [['color', 'Color'], ['lighting', 'Lighting'], ['material', 'Material'], ['mood', 'Mood']]) {
      if (dir[k]) lines.push(`- **${label}:** ${dir[k]}`)
    }
    lines.push('')
  }

  if (logo.conceptName) {
    lines.push('## Selected Logo', '', `### ${logo.conceptName}`, '', logo.explanation || '', '')
    if (logo.image) lines.push(`![Logo](${logo.image})`, '')
    lines.push('')
  }

  if (rules.summary) lines.push('## Summary', '', rules.summary, '')
  if (rules.logoRule) lines.push('## Logo Rules', '', rules.logoRule, '')

  if (Object.keys(dna).length) {
    lines.push('## Visual DNA — 8 dimensions', '', dimText(dna))
  }

  if (rules.doDont) {
    lines.push('### Overall DO', '', ...arr(rules.doDont.do).map((x) => `- ${x}`), '', "### Overall DON'T", '', ...arr(rules.doDont.dont).map((x) => `- ${x}`), '')
  }

  return lines.join('\n')
}